---
- name: Create group 982
  ansible.builtin.group:
    name: "982"
    state: present
    gid: 982

- name: Ensure dockeruser group exists
  ansible.builtin.group:
    name: "dockeruser"
    state: present

- name: Create users and add to groups with password
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "982,dockeruser"
    append: true
    home: "/home/{{ item }}"
    create_home: true
    shell: "/bin/bash"
    password: "{{ 'default-password' | password_hash('sha512') }}"
  loop:
    - dmorgaleva
    - vroskolotko


- name: Generate SSH keys for users
  ansible.builtin.openssh_keypair:
    path: "/home/{{ item }}/{{ item }}_gitlab"
    type: rsa
    size: 2048
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
  loop:
    - dmorgaleva
    - vroskolotko

- name: Set proper ownership for home directories
  ansible.builtin.file:
    path: "/home/{{ item }}"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    recurse: true
  loop:
    - dmorgaleva
    - vroskolotko